version: "3.8"

services:
  examich_frontend:
    build: ./frontend
    profiles:
      - frontend
      - all
    ports:
      - 4200:80

  examich_backend:
    build: ./backend/Examich
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      DOTNET_GENERATE_ASPNET_CERTIFICATE: "true"
    profiles:
      - backend
      - all
    ports:
      - 5000:80
      - 5001:443
    depends_on:
      - examich_db
    links:
      - examich_db

  examich_db:
    image: postgres
    ports:
      - 5432:5432
    profiles:
      - backend
      - db
      - all
    environment:
      POSTGRES_USER: examich_backend_system
      POSTGRES_PASSWORD: justaplaceholder
      POSTGRES_DB: examich
